#!/bin/bash

current_php=$(php --version | head -n 1 | cut -d " " -f 2 | cut  -c-3)

function printUsage() {
	echo "Usage: sudo php_xdebug [options]"
	echo ""
	echo "All the available php_xdebug options are:"
	echo "  -h, --help        Show this help message and exit"
	echo "  -e, --enable      Enables xdebug on the actual php version"
	echo "  -d, --disable     Enables xdebug on the actual php version"
	echo ""
	exit 0
}

function enableXdebugPhp() {
    # set mods available path in variable
    mods_available_path="/etc/php/${current_php}/mods-available"
    # set xdebug.ini path in variable
    xdebug_ini_path="${mods_available_path}/xdebug.ini"
    # set xdebug.ini template path
    xdebug_ini_template_path="$HOME/xdebug.ini.template"
    # set variable with WSL ip found in /etc/resolv.conf
    wsl_ip=$(tail -n 1 /etc/resolv.conf | head -n 4 | cut -d " " -f 2 | cut  -c-12)

    # stop current_php php-fpm with sudo service
    sudo service php${current_php}-fpm stop

    # if xdebug_ini_path exists, delete it with sudo
    if [ -f "${xdebug_ini_path}" ]; then
        sudo rm "${xdebug_ini_path}"
    fi

    # copy xdebug.ini template to mods-available with sudo
    sudo cp "${xdebug_ini_template_path}" "${xdebug_ini_path}"

    # replace %IP% with wsl ip in xdebug.ini
    sudo sed -i "s/%IP%/${wsl_ip}/g" "${xdebug_ini_path}"

    # enable xdebug.ini with phpenmod
    sudo phpenmod -v ${current_php} xdebug

    # start current_php php-fpm with sudo and service
    sudo service php${current_php}-fpm start
}

function disableXdebugPhp() {
    # set mods available path in variable
    mods_available_path="/etc/php/${current_php}/mods-available"
    # set xdebug.ini path in variable
    xdebug_ini_path="${mods_available_path}/xdebug.ini"

    # stop current_php php-fpm with sudo service
    sudo service php${current_php}-fpm stop

    # if xdebug_ini_path exists, delete it with sudo
    if [ -f "${xdebug_ini_path}" ]; then
        sudo rm "${xdebug_ini_path}"
    fi

    # start current_php php-fpm with sudo and service
    sudo service php${current_php}-fpm start
}

while true; do
    case "$1" in
		-h|--help )
		printUsage;
		shift ;;

		-e|--enable )
		ENABLE="1";
		shift ;
		shift ;;

		-d|--disable )
		DISABLE="1"
		shift ;
		shift ;;

		* )
		break ;;
	esac
done

if [ "${ENABLE}" != "1" ] && [ "${DISABLE}" != '1' ]; then
	echo "Use only one of the following options: -e or -d"
	exit 1;
fi

if [ "$(php -m | grep xdebug)" != "" ] && [ "${ENABLE}" == "1" ]; then
    echo "xdebug is already enabled"
    exit 1;
fi

if [ "$(php -m | grep xdebug)" == "" ] && [ "${DISABLE}" == "1" ]; then
    echo "xdebug is already disabled"
    exit 1;
fi

# enable xdebug
if [ "${ENABLE}" == "1" ]; then
    enableXdebugPhp
fi

# disable xdebug
if [ "${DISABLE}" == "1" ]; then
    disableXdebugPhp
fi

exit 0;