#!/bin/bash

stop_php () {
    # set current php version in variable
    current_php=$(php --version | head -n 1 | cut -d " " -f 2 | cut  -c-3)
    # start current_php php-fpm with sudo and service
    sudo service php${current_php}-fpm stop
}

stop_php
sudo service nginx stop
sudo service mysql stop
sudo service elasticsearch stop
sudo service redis-server stop
#sudo service rabbitmq-server stop