# para aplicar cambios en la VM `vagrant reload`
vm:
    memory: 4096
    cpus: 2
    ip_address: "192.168.30.102"
    forwarded_ssh_port: 3102
    hostname: "mywebsite.localhost"

host:
    project_root: "./project"

mysql:
    # Este valor s칩lo se usar치 para el primer provision
    root_password: "root"

git:
    name: "John Doe"
    email: "john.doe@example.com"
    # El editor s칩lo puede ser uno v치lido e instalado en el sistema (vim, nano...)
    editor: "vim"